Repository DuruDuru-UMC-7th/Backend-DuruDuru, pull requests merged in 2025-01, with the labels that each got.

#2 Chore: 프로젝트 디렉토리 초기 설정
  .DS_Store
  Dockerfile
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/backend/.DS_Store
  src/main/java/com/backend/DuruDuru/global/apiPayload/ApiResponse.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/BaseCode.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/GeneralException.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/handler/MemberHandler.java
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/config/SwaggerConfig.java
  src/main/java/com/backend/DuruDuru/global/config/WebConfig.java
  src/main/java/com/backend/DuruDuru/global/converter/MemberConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/common/BaseEntity.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/TestEnum.java
  src/main/java/com/backend/DuruDuru/global/repository/MemberRepository.java
  src/main/java/com/backend/DuruDuru/global/service/MemberService/MemberCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/MemberController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Member/MemberRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Member/MemberResponseDTO.java
Labels: Chore

#4 Chore: github actions CI/CD 설정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/github-actions.yml
Labels: Chore

#5 Refactor: github-actions.yml 파일 수정
  .github/workflows/github-actions.yml
Labels: Refactor

#7 Chore: build.gradle 파일 dependencies 수정
  build.gradle
Labels: Chore

#8 Refactor: build.gradle 수정
  build.gradle
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
Labels: Refactor

#10 Chore: 스웨거 명시를 위한 뼈대 예시 API 작성 및 성공응답 목록 작성
  build.gradle
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/web/controller/ExampleController.java
Labels: Chore

#11 Refactor: github-actions.yml 파일 수정
  .github/workflows/github-actions.yml
Labels: Refactor

#12 Refactor: github-action.yml 수정
  .github/workflows/github-actions.yml
Labels: Refactor

#13 Refactor: CI/CD 기존 컨테이너 중지 및 제거 명령 추가
  .github/workflows/github-actions.yml
Labels: Refactor

#16 Feat: 식재료 관련 API 뼈대 작성
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
Labels: Feature

#18 Feat: Entity 설계
  src/main/java/com/backend/DuruDuru/DuruDuruApplication.java
  src/main/java/com/backend/DuruDuru/global/domain/common/BaseEntity.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Address.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Chatting.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/ChattingRoom.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Fridge.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Ingredient.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/MemberAddress.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/MemberImg.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/MemberRecipe.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Message.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Notification.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Recipe.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/RecipeIngredient.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Town.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Trade.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/TradeImg.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/Gender.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/NotificationType.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/Status.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/Status.java~
  src/main/java/com/backend/DuruDuru/global/domain/enums/StorageType.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/TestEnum.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/TradeType.java
Labels: :sparkles: Feature

#20 Feat: JWT 설정
  build.gradle
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/AuthException.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/handler/AuthHandler.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/handler/AuthHandler.java~
  src/main/java/com/backend/DuruDuru/global/repository/MemberRepository.java
  src/main/java/com/backend/DuruDuru/global/security/filter/JwtRequest.java~
  src/main/java/com/backend/DuruDuru/global/security/filter/JwtRequestFilter.java
  src/main/java/com/backend/DuruDuru/global/security/handler/annotation/AuthUser.java
  src/main/java/com/backend/DuruDuru/global/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/com/backend/DuruDuru/global/security/handler/resolver/AuthUserArgumentResolver.java~
  src/main/java/com/backend/DuruDuru/global/security/principal/PrincipalDetails.java
  src/main/java/com/backend/DuruDuru/global/security/principal/PrincipalDetailsService.java
  src/main/java/com/backend/DuruDuru/global/security/provider/JwtTokenProvider.java
  src/main/resources/application.yml~
Labels: :sparkles: Feature

#22 Feat: 레시피 Controller 뼈대 구현
  src/main/java/com/backend/DuruDuru/global/web/controller/RecipeController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Recipe/RecipeRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Recipe/RecipeResponseDTO.java
  src/main/resources/application.yml~
Labels: :sparkles: Feature

#23 Feat: 냉장고 관련 API 뼈대 작성
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/web/controller/FridgeController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
Labels: :sparkles: Feature

#24 Refactor: build.gradle 수정 및 냉장고 컨트롤러 메소드 수정
  build.gradle
  src/main/java/com/backend/DuruDuru/global/web/controller/FridgeController.java
Labels: :recycle: Refactor

#25 Refactor: SecurityConfig jwt 필터처리 부분 수정
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/security/provider/JwtTokenProvider.java
Labels: :recycle: Refactor

#26 Refactor: JwtTokenProvider 파일 수정
  src/main/java/com/backend/DuruDuru/global/security/provider/JwtTokenProvider.java
Labels: :recycle: Refactor

#31 Feat: 멤버 Controller - 지도, 품앗이 부분 뼈대 구현
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/web/controller/MemberController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/TradeController.java
Labels: :sparkles: Feature

#35 Refactor: 식재료 컨트롤러 API 엔드포인트 수정
  src/main/java/com/backend/DuruDuru/global/security/provider/JwtTokenProvider.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
Labels: :recycle: Refactor

#37 Chore: CI/CD 도커 설정 변경
  .github/workflows/github-actions.yml
  Dockerfile
Labels: :gear: Chore

#38 Chore: github-actions.yml 파일 신텍스 오류 수정
  .github/workflows/github-actions.yml
Labels: :gear: Chore

#50 Feat: LikeTrade 엔티티 추가
  src/main/java/com/backend/DuruDuru/global/domain/entity/LikeTrade.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Trade.java
Labels: :sparkles: Feature

#52 Feat: CLOVA OCR을 활용한 영수증 분석 및 구매 식재료 목록 반환 API 기능 구현
  build.gradle
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/ClovaOCRReceiptService.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/OCRController.java
Labels: :sparkles: Feature

#54 Chore: CI/CD Deploy 환경변수 주입 수정
  .github/workflows/github-actions.yml
Labels: :gear: Chore

#55 Chore: CI/CD 설정 github-actions.yml 파일 수정
  .github/workflows/github-actions.yml
Labels: :gear: Chore

#57 Chore: application.properties 파일 제거
  src/main/resources/application.properties
Labels: :gear: Chore

#58 Chore: CI/CD github-actions.yml 파일 resources 폴더 생성 로직 추가
  .github/workflows/github-actions.yml
Labels: :gear: Chore

#63 Feat: AuthUserArgumentResolver 구현
  build.gradle
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/handler/MemberException.java
  src/main/java/com/backend/DuruDuru/global/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/com/backend/DuruDuru/global/service/MemberService/MemberCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/MemberService/MemberCommandServiceImpl.java
Labels: :sparkles: Feature

#65 Refactor: entity 수정
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Town.java
  src/main/resources/application.yml~
Labels: :recycle: Refactor

#71 Feat: 식재료 대분류, 소분류 카테고리 엔티티 생성 및 매핑 엔티티 추가 및 매핑 엔티티 생성
  src/main/java/com/backend/DuruDuru/global/domain/entity/Ingredient.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/IngredientCategory.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/MajorCategory.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/MinorCategory.java
  src/main/resources/application.yml~
Labels: :sparkles: Feature

#75 Refactor: 회원가입, 로그인 API 권한 허용
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#78 Feat: 식재료 직접 등록, 수정, 삭제 API 기능 구현
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java~
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Ingredient.java
  src/main/java/com/backend/DuruDuru/global/repository/FridgeRepository.java
  src/main/java/com/backend/DuruDuru/global/repository/IngredientRepository.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#80 Refactor: 식재료, 냉장고 관련 API 엔트포인트 수정 및 security config 파일 수정
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/web/controller/FridgeController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
Labels: :recycle: Refactor

#82 Feat: 식재료 구매 날짜 및 보관 방식 등록 API 기능 구현
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Fridge.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Ingredient.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/StorageType.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#84 Feat: 내 동네 등록, 조회, 수정 API 구현
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/converter/MemberConverter.java~
  src/main/java/com/backend/DuruDuru/global/converter/TownConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Town.java
  src/main/java/com/backend/DuruDuru/global/repository/TownRepository.java
  src/main/java/com/backend/DuruDuru/global/service/TownService/TownCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/TownService/TownCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/service/TownService/TownQueryService.java
  src/main/java/com/backend/DuruDuru/global/service/TownService/TownQueryServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/MemberController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/TownController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/TradeController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Town/TownRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Town/TownResponseDTO.java
Labels: :sparkles: Feature

#86 Feat: 구매한 식재료 사진 등록 API 기능 구현
  src/main/java/com/backend/DuruDuru/global/S3/AmazonS3Manager.java
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/repository/IngredientImageRepository.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#88 Feat: 식재료 대분류, 소분류 카테고리 설정 API 구현
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Ingredient.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/IngredientCategory.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/MajorCategory.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/MinorCategory.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/MajorCategory.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/MinorCategory.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientQueryService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientQueryServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#90 Feat: 소분류 카테고리에 속하는 식재료 리스트 조회 API 구현
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/repository/IngredientRepository.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientQueryService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientQueryServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#93 Feat: 식재료 이름으로 검색하는 API 구현
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/repository/IngredientRepository.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientQueryService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientQueryServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#97 Feat: OCR 영수증 인식 후 식재료 목록 저장 및 자동 카테고리 설정 API 구현
  .gitignore
  build.gradle
  src/main/java/com/backend/DuruDuru/global/domain/enums/MajorCategory.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/MinorCategory.java
  src/main/java/com/backend/DuruDuru/global/security/provider/KakaoAuthProvider.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/CategoryMapper.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/ClovaOCRReceiptService.java
  src/main/java/com/backend/DuruDuru/global/web/controller/OCRController.java
Labels: :sparkles: Feature

#98 Feat: OCR 영수증 인식 후 식재료 목록 저장 및 자동 카테고리 설정 API 구현
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/CategoryMapper.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/ClovaOCRReceiptService.java
  src/main/java/com/backend/DuruDuru/global/web/controller/OCRController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#99 Feat: 영수증 인식된 식재료 이름 수정 및 구매 수량 변경 API 구현
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Ingredient.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Receipt.java
  src/main/java/com/backend/DuruDuru/global/repository/ReceiptRepository.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/ClovaOCRReceiptService.java
  src/main/java/com/backend/DuruDuru/global/web/controller/OCRController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#101 Fix: SwaggerConfig 엔드포인트 오타로 인한 스웨거 오류 해결
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#102 Feat: 영수증 인식 식재료 전체 구매 날짜 변경 API 구현
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Receipt.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/ClovaOCRReceiptService.java
  src/main/java/com/backend/DuruDuru/global/web/controller/ExampleController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/controller/OCRController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#103 Feat: 영수증 인식된 식재료의 보관방식 및 소비기한 자동 설정 구현
  src/main/java/com/backend/DuruDuru/global/converter/IngredientConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/MinorCategory.java
  src/main/java/com/backend/DuruDuru/global/service/IngredientService/IngredientCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/service/OCRService/ClovaOCRReceiptService.java
  src/main/java/com/backend/DuruDuru/global/web/controller/IngredientController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Ingredient/IngredientResponseDTO.java
Labels: :sparkles: Feature

#104 Feat: 품앗이 게시글 등록, 조회 API 구현
  src/main/java/com/backend/DuruDuru/global/converter/TradeConverter.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Member.java
  src/main/java/com/backend/DuruDuru/global/domain/entity/Trade.java
  src/main/java/com/backend/DuruDuru/global/domain/enums/TradeType.java
  src/main/java/com/backend/DuruDuru/global/repository/TradeRepository.java
  src/main/java/com/backend/DuruDuru/global/service/TradeService/TradeCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/TradeService/TradeCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/service/TradeService/TradeQueryService.java
  src/main/java/com/backend/DuruDuru/global/service/TradeService/TradeQueryServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/TradeController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Trade/TradeRequestDTO.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Trade/TradeResponseDTO.java
Labels: :sparkles: Feature

#105 Refactor: trade 엔드포인트 수정
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#106 Refactor: Town 엔드포인트 수정
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#107 Refactor: Trade 관련 접근 수정
  src/main/java/com/backend/DuruDuru/global/config/SecurityConfig.java
  src/main/java/com/backend/DuruDuru/global/converter/TradeConverter.java
Labels: :recycle: Refactor

#109 Feat: 특정 레시피 조회 API
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/backend/DuruDuru/global/apiPayload/exception/RecipeException.java
  src/main/java/com/backend/DuruDuru/global/converter/RecipeConverter.java
  src/main/java/com/backend/DuruDuru/global/repository/RecipeRepository.java
  src/main/java/com/backend/DuruDuru/global/service/RecipeService/RecipeCommandService.java
  src/main/java/com/backend/DuruDuru/global/service/RecipeService/RecipeCommandServiceImpl.java
  src/main/java/com/backend/DuruDuru/global/web/controller/RecipeController.java
  src/main/java/com/backend/DuruDuru/global/web/dto/Recipe/RecipeResponseDTO.java
Labels: :sparkles: Feature
